export const DEFAULT_HANDOFF_FLOW = {
  flow_name: "Global: Human Handoff",
  layout_left_to_right: true,
  nodes: [
    {
      id: "node_trigger_handoff",
      type: "trigger",
      position: { x: 100, y: 200 },
      data: {
        label: "Support Trigger",
        triggerType: "keyword",
        triggerKeywords: "human, agent, help desk, live agent",
      },
    },
    {
      id: "node_confirm_handoff",
      type: "menu",
      position: { x: 400, y: 200 },
      data: {
        label: "Confirm Transfer",
        text: "Would you like me to transfer you to a human support agent?",
        item1: "Yes, please",
        item2: "No, I'm good",
        timeout: 86400,
        reminderDelay: 43200,
        reminderText: "Hi there! Just checking in—did you still want to speak to an agent?",
      },
    },
    {
      id: "node_wait_msg",
      type: "message",
      position: { x: 700, y: 50 },
      data: {
        label: "Wait Message",
        text: "Please wait a moment while I connect you with our next available agent...",
      },
    },
    {
      id: "node_assign_agent",
      type: "assign_agent",
      position: { x: 1000, y: 50 },
      data: { label: "Transfer to Human" },
    },
    {
      id: "node_cancel_msg",
      type: "message",
      position: { x: 700, y: 200 },
      data: { label: "Cancel Handoff", text: "No problem! Let me know if you need anything else." },
    },
    {
      id: "node_timeout_msg",
      type: "message",
      position: { x: 700, y: 350 },
      data: { label: "Timeout Notice", text: "This request has timed out due to inactivity. Type 'Help' whenever you need us!" },
    },
    {
      id: "node_end_handoff",
      type: "end",
      position: { x: 1300, y: 200 },
      data: { label: "End Session" },
    },
  ],
  edges: [
    { id: "e1", source: "node_trigger_handoff", target: "node_confirm_handoff", sourceHandle: "next" },
    { id: "e2", source: "node_confirm_handoff", target: "node_wait_msg", sourceHandle: "item1" },
    { id: "e3", source: "node_confirm_handoff", target: "node_cancel_msg", sourceHandle: "item2" },
    { id: "e_timeout", source: "node_confirm_handoff", target: "node_timeout_msg", sourceHandle: "timeout" },
    { id: "e4", source: "node_wait_msg", target: "node_assign_agent", sourceHandle: "next" },
    { id: "e5", source: "node_assign_agent", target: "node_end_handoff", sourceHandle: "next" },
    { id: "e6", source: "node_cancel_msg", target: "node_end_handoff", sourceHandle: "next" },
    { id: "e7", source: "node_timeout_msg", target: "node_end_handoff", sourceHandle: "next" },
  ],
} as const;

export const DEFAULT_CSAT_FLOW = {
  flow_name: "Post-Handoff CSAT",
  layout_left_to_right: true,
  nodes: [
    {
      id: "node_resume_csat",
      type: "resume_bot",
      position: { x: 100, y: 200 },
      data: { label: "Agent Closed Chat", resumeMode: "restart", resumeText: "Your support ticket has been closed by the agent." },
    },
    {
      id: "node_csat_menu",
      type: "menu",
      position: { x: 400, y: 200 },
      data: {
        label: "Rate Experience",
        text: "How was your experience with our support team today?",
        item1: "Excellent 🌟",
        item2: "Average 😐",
        item3: "Poor 😞",
        timeout: 86400,
        reminderDelay: 43200,
        reminderText: "We'd love to hear your feedback! Please tap a rating above.",
      },
    },
    {
      id: "node_excellent_msg",
      type: "message",
      position: { x: 700, y: 50 },
      data: { label: "Thank You", text: "That is wonderful to hear! Thank you for reaching out, and have a great day." },
    },
    {
      id: "node_sorry_msg",
      type: "message",
      position: { x: 700, y: 250 },
      data: { label: "Apology", text: "We are very sorry to hear that we did not meet your expectations." },
    },
    {
      id: "node_capture_issue",
      type: "input",
      position: { x: 1000, y: 250 },
      data: {
        label: "Capture Complaint",
        text: "Please explain your issue below. A senior member from our team will review this.",
        variable: "csat_complaint_text",
        validation: "text",
        timeout: 86400,
        reminderDelay: 43200,
        reminderText: "Are you still there? Please type your issue so our management team can review it.",
      },
    },
    {
      id: "node_save_complaint",
      type: "save",
      position: { x: 1300, y: 250 },
      data: { label: "Save to Lead", variable: "csat_complaint_text", leadField: "escalation_notes" },
    },
    {
      id: "node_end_csat",
      type: "end",
      position: { x: 1600, y: 200 },
      data: { label: "End Session" },
    },
  ],
  edges: [
    { id: "e1", source: "node_resume_csat", target: "node_csat_menu", sourceHandle: "next" },
    { id: "e2", source: "node_csat_menu", target: "node_excellent_msg", sourceHandle: "item1" },
    { id: "e3", source: "node_csat_menu", target: "node_sorry_msg", sourceHandle: "item2" },
    { id: "e4", source: "node_csat_menu", target: "node_sorry_msg", sourceHandle: "item3" },
    { id: "e_timeout1", source: "node_csat_menu", target: "node_end_csat", sourceHandle: "timeout" },
    { id: "e5", source: "node_sorry_msg", target: "node_capture_issue", sourceHandle: "next" },
    { id: "e6", source: "node_capture_issue", target: "node_save_complaint", sourceHandle: "response" },
    { id: "e_timeout2", source: "node_capture_issue", target: "node_end_csat", sourceHandle: "timeout" },
    { id: "e7", source: "node_excellent_msg", target: "node_end_csat", sourceHandle: "next" },
    { id: "e8", source: "node_save_complaint", target: "node_end_csat", sourceHandle: "next" },
  ],
} as const;
